macro(setup_standard_vars)
    set(TOOLS_PREFIX ${CMAKE_INSTALL_PREFIX})
    set(TOOLS_EXEC_PREFIX ${TOOLS_PREFIX})
    set(TOOLS_BIN_DIR ${TOOLS_EXEC_PREFIX}/bin)
    set(TOOLS_LIB_DIR ${TOOLS_EXEC_PREFIX}/lib)
    set(TOOLS_INCLUDE_DIR ${TOOLS_PREFIX}/include)
    set(TOOLS_DATA_ROOT_DIR ${TOOLS_PREFIX}/share)
    set(TOOLS_DATA_DIR ${TOOLS_DATA_ROOT_DIR})
    set(TOOLS_MAN_DIR ${TOOLS_DATA_ROOT_DIR}/man)
    set(TOOLS_INFO_DIR ${TOOLS_DATA_ROOT_DIR}/info)
    set(TOOLS_PKG_CONFIG_DIR ${TOOLS_DATA_ROOT_DIR}/pkgconfig)
    if(CMAKE_VERBOSE_MAKEFILE)
        message(STATUS "TOOLS_PREFIX            : ${TOOLS_PREFIX}")
        message(STATUS "TOOLS_EXEC_PREFIX       : ${TOOLS_EXEC_PREFIX}")
        message(STATUS "TOOLS_BIN_DIR           : ${TOOLS_BIN_DIR}")
        message(STATUS "TOOLS_LIB_DIR           : ${TOOLS_LIB_DIR}")
        message(STATUS "TOOLS_INCLUDE_DIR       : ${TOOLS_INCLUDE_DIR}")
        message(STATUS "TOOLS_DATA_ROOT_DIR     : ${TOOLS_DATA_ROOT_DIR}")
        message(STATUS "TOOLS_DATA_DIR          : ${TOOLS_DATA_DIR}")
        message(STATUS "TOOLS_MAN_DIR           : ${TOOLS_MAN_DIR}")
        message(STATUS "TOOLS_INFO_DIR          : ${TOOLS_INFO_DIR}")
        message(STATUS "TOOLS_PKG_CONFIG_DIR    : ${TOOLS_PKG_CONFIG_DIR}")
    endif()
endmacro()
