function(setup_target_properties_library target)
    if (WIN32 OR APPLE)
        if (BUILD_SHARED_LIBS)
            target_compile_definitions(${target} PRIVATE _USRDLL)
        endif()
    elseif (UNIX)
    endif()
endfunction()
